// src/utils/exportUtils.js
// Real CSV and PDF export functions

// ---------- CSV EXPORT ----------
export function downloadCSV({ filename, columns, candidates }) {
  const headers = columns.map(c => c.label)
  const rows = candidates.map(c => {
    return columns.map(col => {
      const val = c[col.key]
      const str = String(val ?? '')
      return str.includes(',') || str.includes('"') ? `"${str.replace(/"/g, '""')}"` : str
    })
  })

  const csvContent = [headers, ...rows].map(row => row.join(',')).join('\n')

  const blob = new Blob(['\uFEFF' + csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename || 'export.csv'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// ---------- PDF EXPORT ----------
export async function downloadPDF({ filename, title, orientation, candidates, jobTitle, options }) {
  const { default: jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default

  const doc = new jsPDF({
    orientation: orientation === 'Landscape' ? 'landscape' : 'portrait',
    unit: 'pt',
    format: 'a4'
  })

  const pageWidth = doc.internal.pageSize.getWidth()

  doc.setFillColor(26, 43, 92)
  doc.rect(0, 0, pageWidth, 60, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('CVision AI Report', 40, 30)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(title || 'Candidate Evaluation Summary', 40, 48)

  doc.setTextColor(60, 60, 60)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text(`Position: ${jobTitle || 'N/A'}`, 40, 90)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 40, 105)
  doc.text(`Total Candidates: ${candidates.length}`, 40, 118)

  let cursorY = 140
  if (options?.charts) {
    const highly = candidates.filter(c => c.recommendation === 'Highly Recommended').length
    const recommended = candidates.filter(c => c.recommendation === 'Recommended').length
    const notRec = candidates.filter(c => c.recommendation === 'Not Recommended').length
    const avgMatch = Math.round(candidates.reduce((s, c) => s + c.match, 0) / candidates.length) || 0

    doc.setFont('helvetica', 'bold')
    doc.setFontSize(12)
    doc.text('Summary Analytics', 40, cursorY)
    cursorY += 15

    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.text(`- Highly Recommended: ${highly}`, 50, cursorY); cursorY += 14
    doc.text(`- Recommended: ${recommended}`, 50, cursorY); cursorY += 14
    doc.text(`- Not Recommended: ${notRec}`, 50, cursorY); cursorY += 14
    doc.text(`- Average AI Match: ${avgMatch}%`, 50, cursorY); cursorY += 24
  }

  const tableColumns = [
    { header: 'Rank', dataKey: 'rank' },
    { header: 'Candidate Name', dataKey: 'name' },
    { header: 'Applied For', dataKey: 'appliedFor' },
    { header: 'AI Match', dataKey: 'match' },
    { header: 'Recommendation', dataKey: 'recommendation' }
  ]

  if (options?.emails) {
    tableColumns.splice(3, 0, { header: 'Email', dataKey: 'email' })
  }

  const tableRows = candidates.map(c => ({
    rank: `#${String(c.rank).padStart(2, '0')}`,
    name: c.name,
    appliedFor: c.appliedFor,
    match: `${c.match}%`,
    recommendation: c.recommendation,
    email: c.email
  }))

  autoTable(doc, {
    startY: cursorY,
    head: [tableColumns.map(c => c.header)],
    body: tableRows.map(r => tableColumns.map(c => r[c.dataKey])),
    theme: 'striped',
    headStyles: { fillColor: [26, 43, 92], textColor: 255, fontStyle: 'bold' },
    bodyStyles: { fontSize: 9, textColor: [40, 40, 40] },
    alternateRowStyles: { fillColor: [245, 246, 248] },
    margin: { left: 40, right: 40 }
  })

  if (options?.branding) {
    const pageCount = doc.internal.getNumberOfPages()
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i)
      const pageH = doc.internal.pageSize.getHeight()
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.text('Generated by CVision AI', 40, pageH - 20)
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 100, pageH - 20)
    }
  }

  doc.save(filename || 'candidate_report.pdf')
}
